export declare const UNSET: Readonly<{}>;
export declare const OBJECT: any;
export declare const JSON_OBJECT: string;
export declare const ARRAY: readonly any[];
export declare const JSON_ARRAY: string;
export declare const FOREVER = true;
export declare const MAX_PERCENTAGE = 100;
export declare const KB = 1024;
export declare const MB: number;
export declare const GB: number;
export declare const TB: number;
export declare const PB: number;
