export declare const KeyboardKey: {
    ESCAPE: string;
    SHIFT: string;
    ALT: string;
    CTRL: string;
    ARROW_LEFT: string;
    ARROW_RIGHT: string;
    NUM0: string;
    NUM1: string;
    NUM2: string;
    NUM3: string;
    NUM4: string;
    NUM5: string;
    NUM6: string;
    NUM7: string;
    NUM8: string;
    NUM9: string;
    PLUS: string;
    MINUS: string;
    E: string;
};
export declare const KeyboardCode: {
    ESCAPE: number;
    SHIFT: number;
    CTRL: number;
    ALT: number;
    NUM0: number;
    NUM1: number;
    NUM2: number;
    NUM3: number;
    NUM4: number;
    NUM5: number;
    NUM6: number;
    NUM7: number;
    NUM8: number;
    NUM9: number;
    META: number;
    C: number;
};
